### ISSUE TITLE
Indexing fails silently with switching to Elasticsearch 5 library

### ISSUE THREAD

**Issue by gnanet** [Invertus/brad#1]
Distributor ID: Debian
Release:        8.6
PHP version: 5.6.27-0+deb8u1
php5-json version: 1.3.6-1

**EDIT: The issue of [missing constants](https://github.com/elastic/elasticsearch-php/issues/498) was resolved in php5-json version 1.3.7, the docs also contain the [php version requirement](https://github.com/elastic/elasticsearch-php/blob/5.0/docs/php-version-requirement.asciidoc)**

Followed the instructions about switching to Elasticsearch 5 library, module was installed, but index creation ignored shard and replica parameters, and reindexing products failed also with notable reason.

error_log contained:

> PHP message: PHP Warning:  json_encode() expects parameter 2 to be long, string given in MANGLED_PATH/modules/brad/vendor/elasticsearch/elasticsearch/src/Elasticsearch/Serializers/SmartSerializer.php on line 30

The mentioned line 30 contained:

` $data = json_encode($data, JSON_PRESERVE_ZERO_FRACTION);`

A quick search pointed to a change in Elasticsearch 5 library described in [Pull Request 481](https://github.com/elastic/elasticsearch-php/pull/481)

Based on the error message, i assumed that JSON_PRESERVE_ZERO_FRACTION was not a reserved constant, and replacing it with the numeric value referred in the [comment of the PHP manual about JSON Predefined Constants](http://php.net/manual/en/json.constants.php#118371) resolved the issues.

These constants should be already predefined since PHP 5.6.6, but according to a [thread on the Debian forums](http://forums.debian.net/viewtopic.php?f=17&t=124985) it was not the case with PHP 5.6.13 either, also there seems no bugreports about this.

I agree that fixing of this issue should be done by upstream, but if any user is facing this issue, my report can help, to work around it.

**Comment by sarjon** [comment]
Hi, thanks a lot for your contribution and providing a great explanation!

**Comment by gnanet** [comment]
I want to extend the search with textual content from Product datasheet PDF-files, and i will try to extend this great piece of software, i think i will fork and start working on it
