### ISSUE TITLE
Brad on localhost?

### ISSUE THREAD

**Issue by PrestaShark** [Invertus/brad#11]
Hi! How to make it work on XAMP localhost?

**Comment by rokaszygmantas** [comment]
Hi @PrestaShark!
To make Brad work on your local environment you will need Elasticsearch service running on your (or another) computer and connect it to the module via module's configuration.
You can find Elasticsearch installation instructions and download link here: https://www.elastic.co/downloads/elasticsearch
You can find Brad's installation instructions here:
https://github.com/Invertus/brad/blob/v2/README.md

Let me know if it works out!
