### ISSUE TITLE
Need "total number of fields in mapping" setting

### ISSUE THREAD

**Issue by yavuzaydin** [Invertus/brad#13]
Getting error:
[2017-12-08T15:05:31,879][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [JXcGHXq] failed to put mappings on indices [[[brzxb2zb_1/oXaMGoKERyCOpulhJGTC6g]]], type [products]
java.lang.IllegalArgumentException: Limit of total fields [1000] in index [brzxb2zb_1] has been exceeded

Further searching on this error led me to:
https://github.com/elastic/elasticsearch/pull/17357

I just tried adding this setting to the buildIndex function in src/Service/Elasticsearch/Builder/IndexBuilder.php and in my situation I can set this value to 2000 and it fixes this error.

However I think a proper resolution would be to add an adjustable default sane value in the backend.

**Comment by sarjon** [comment]
Hi, it's a known issues, we will update it in the future.
