### ISSUE TITLE
Is this working with PS 1.7

### ISSUE THREAD

**Issue by rdy4ever** [Invertus/brad#16]
Hi. Could you tell me if Brad works for prestashop 1.7.x or are there any plans to make a compatible version of Brad? 1.6 will be EOL this autumn. Thank you!

**Comment by simonasinvertus** [comment]
Thank you for showing interest in our module.
This module currently support only PS1.6
We you have plans to develop PS1.7 version.

If you want our help with integrating Brad into your shop please contact us marketing@invertus.eu

**Comment by x0rzkov** [comment]
Any updates on the 1.7 version ? I would like to extend your module with some widgets from https://github.com/appbaseio/reactivesearch

**Comment by simonasinvertus** [comment]
Thank you for showing interest in our module. We don't have plans to release 1.7 version in public, however if you are interested in custom development please contact us marketing@invertus.eu
