### ISSUE TITLE
Failed to index products

### ISSUE THREAD

**Issue by nicdnepr** [Invertus/brad#18]
Hi
I use brad with elastic 6, elastic is runnig
I fixed composer.json to `"elasticsearch/elasticsearch": "~6.0"`, run update, zip and install module
Then I run in colsole  php /home/.../modules/brad/brad.cron.php  index_products 1 all 
 
And I get error `Failed to index products`
Any suggest? I'm new with elastic

**Comment by sarjon** [comment]
Hi,

first of all, thanks for showing your interes in using brad module. :slightly_smiling_face: 

Unfortunately, brad was not tested on Elasticsearch 6 and thus it may be the reason why it fails to index products. What I suggest you to do is take a look at `brad/logs/logs.log` file to see if there are any useful information that would potentialy help debug indexing issue.

**Comment by nicdnepr** [comment]
Yes the problem is elastic 6
errors is
```
Failed to create index: {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [reference]"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [products]: No handler for type [string] declared on field [reference]","caused_by":{"type":"mapper_parsing_exception","reason":"No handler for type [string] declared on field [reference]"}},"status":400} [] []
```
code is here 
https://github.com/Invertus/brad/blob/v2/src/Service/Elasticsearch/Builder/IndexBuilder.php#L78
https://github.com/Invertus/brad/blob/v2/src/Service/Elasticsearch/Builder/IndexBuilder.php#L152
I fixed it local

Also error
```
brad_logger.ERROR: Failed to create index: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"Rejecting mapping update to [ufzdygnm_1] as the final mapping would have more than 1 type: [categories, products]"}],"type":"illegal_argument_exception","reason":"Rejecting mapping update to [ufzdygnm_1] as the final mapping would have more than 1 type: [categories, products]"},"status":400} [] []
```
looks code here double index
https://github.com/Invertus/brad/blob/v2/src/Service/Elasticsearch/Builder/IndexBuilder.php#L68
No idea what to do

**Comment by sarjon** [comment]
I checked it a bit more and the problems seems to be backward compatibility break between Elasticsearch 5 and 6 versions. 

Since we don't have any plans for adding support for Elasticsearch 6 any time soon, i'd suggest you to either use Elasticsearch 5 or add support for Elasticsearch 6 on your own (and submit PR for that :wink:) as it is open source module. :slightly_smiling_face: 

I'm closing this issue as it won't be fixed.
