### ISSUE TITLE
Class 'AbstractAdminBradModuleController' not found

### ISSUE THREAD

**Issue by mtahiue** [Invertus/brad#2]
Hi

I've tried both v2 and v2-dev branches 

and the module install throw each time :

"NOTICE: PHP message: PHP Fatal error:  Class 'AbstractAdminBradModuleController' not found in /var/www/html/modules/brad/controllers/admin/AdminBradSettingController.php on line 27"

Could you explain what am i doing wrong ?

Thx for help

**Comment by sarjon** [comment]
Hi, I couldn't reproduce this issue, but I believe there's something wrong with autoloader.

There's a couple things you can try:
1. In v2 branch brad.php file  move $this->requireAutoloader(); after parent::__construct() like so:
`parent::__construct(); `
`$this->requireAutoloader();`

2. If still not working then run `composer dumpautoload` to generate new autoloader file.

If that does not help, please provide more information (like PS version, when exactly this error occurs).

**Comment by veebipoed** [comment]
I had the same issue.

Turned out that the solution was to rename the overrides directory, then settings opened. After opening and setting the correct server I renamed the overrides directory back and the settings kept working.
