### ISSUE TITLE
Search CMS Pages

### ISSUE THREAD

**Issue by netdrag** [Invertus/brad#6]
One of the biggest problems with prestashop-search is that its not possible to search CMS Pages. 
Would that be a possible enhancement for Brad?

I see people often search for invoice or shipping options in the "product search"

**Comment by rokaszygmantas** [comment]
Hello @netdrag, thanks for opening an issue! It is possible to do some custom developing for Brad to include CMS pages search, please reach us out at marketing@invertus.eu for more information.

**Comment by netdrag** [comment]
I maybe code that myself. Just wanted to know if its interesting for other people too
